[launcher]
author = WithSecure
description = Collects EPP Security Events and EDR Broad Context Detections from the WithSecure Elements API.
version = 1.0.0

[package]
id = ta-withsecure-elements

[ui]
is_visible = 1
label = WithSecure Elements Add-on for Splunk

[install]
is_configured = 0
build = 1

[triggers]
reload.inputs = simple
