[id]
name = ta-withsecure-elements
version = 1.0.5

[launcher]
author = WithSecure
description = Collects EPP Security Events and Broad Context Detection (BCD) incidents and detections from the WithSecure Elements API.
version = 1.0.5

[package]
id = ta-withsecure-elements

[ui]
is_visible = 1
label = WithSecure Elements Add-on
default_view = search

[install]
is_configured = 0
build = 7
