[withsecure_epp_input]
python.version = python3
interval = 300
index = main
disabled = 1

[withsecure_bcd_input]
python.version = python3
interval = 300
index = main
auto_fetch_detections = false
disabled = 1
